version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NMAPSCANNER_LAMBDAMODE: "false"
      NMAPSCANNER_LAMBDAFUNCTION: "scan"
      NMAPSCANNER_SCANNER_BINARGS: "-T5"
      NMAPSCANNER_RESULTSURL: "http://localhost/results"
      NMAPSCANNER_STORE_TYPE: "MEMORY"
      NMAPSCANNER_RESULTSPRODUCER_TYPE: "NULL"
      NMAPSCANNER_RESULTSPRODUCER_BENTHOS_YAML: ""
      NMAPSCANNER_RESULTSPRODUCER_POST_ENDPOINT: ""
      NMAPSCANNER_RESULTSPRODUCER_POST_HTTPCLIENT_TYPE: "DEFAULT"
      NMAPSCANNER_RESULTSPRODUCER_POST_HTTPCLIENT_DEFAULTCONFIG_CONTENTTYPE: "application/json"
      NMAPSCANNER_RESULTSPRODUCER_POST_HTTPCLIENT_SMART_OPENAPI: ""
      NMAPSCANNER_WORKPRODUCER_TYPE: "NULL"
      NMAPSCANNER_WORKPRODUCER_BENTHOS_YAML: ""
      NMAPSCANNER_WORKPRODUCER_POST_ENDPOINT: ""
      NMAPSCANNER_WORKPRODUCER_POST_HTTPCLIENT_TYPE: "DEFAULT"
      NMAPSCANNER_WORKPRODUCER_POST_HTTPCLIENT_DEFAULTCONFIG_CONTENTTYPE: application/json
      NMAPSCANNER_WORKPRODUCER_POST_HTTPCLIENT_SMART_OPENAPI: ""
      SERVERFULL_RUNTIME_HTTPSERVER_ADDRESS: ":8081"
      SERVERFULL_RUNTIME_CONNSTATE_REPORTINTERVAL: "5s"
      SERVERFULL_RUNTIME_CONNSTATE_HIJACKEDCOUNTER: http.server.connstate.hijacked
      SERVERFULL_RUNTIME_CONNSTATE_CLOSEDCOUNTER: http.server.connstate.closed
      SERVERFULL_RUNTIME_CONNSTATE_IDLEGAUGE: http.server.connstate.idle.gauge
      SERVERFULL_RUNTIME_CONNSTATE_IDLECOUNTER: http.server.connstate.idle
      SERVERFULL_RUNTIME_CONNSTATE_ACTIVEGAUGE: http.server.connstate.active.gauge
      SERVERFULL_RUNTIME_CONNSTATE_ACTIVECOUNTER: http.server.connstate.active
      SERVERFULL_RUNTIME_CONNSTATE_NEWGAUGE: http.server.connstate.new.gauge
      SERVERFULL_RUNTIME_CONNSTATE_NEWCOUNTER: http.server.connstate.new
      SERVERFULL_RUNTIME_EXPVAR_ALLOC: go_expvar.memstats.alloc
      SERVERFULL_RUNTIME_EXPVAR_FREES: go_expvar.memstats.frees
      SERVERFULL_RUNTIME_EXPVAR_HEAPALLOC: go_expvar.memstats.heap_alloc
      SERVERFULL_RUNTIME_EXPVAR_HEAPIDLE: go_expvar.memstats.heap_idle
      SERVERFULL_RUNTIME_EXPVAR_HEAPINUSE: go_expvar.memstats.heap_inuse
      SERVERFULL_RUNTIME_EXPVAR_HEAPOBJECT: go_expvar.memstats.heap_objects
      SERVERFULL_RUNTIME_EXPVAR_HEAPREALEASED: go_expvar.memstats.heap_released
      SERVERFULL_RUNTIME_EXPVAR_HEAPSTATS: go_expvar.memstats.heap_sys
      SERVERFULL_RUNTIME_EXPVAR_LOOKUPS: go_expvar.memstats.lookups
      SERVERFULL_RUNTIME_EXPVAR_MALLOCS: go_expvar.memstats.mallocs
      SERVERFULL_RUNTIME_EXPVAR_NUMGC: go_expvar.memstats.num_gc
      SERVERFULL_RUNTIME_EXPVAR_PAUSENS: go_expvar.memstats.pause_ns
      SERVERFULL_RUNTIME_EXPVAR_PAUSETOTALNS: go_expvar.memstats.pause_total_ns
      SERVERFULL_RUNTIME_EXPVAR_TOTALALLOC: go_expvar.memstats.total_alloc
      SERVERFULL_RUNTIME_EXPVAR_GOROUTINESEXISTS: go_expvar.goroutines.exists
      SERVERFULL_RUNTIME_EXPVAR_REPORTINTERVAL: "5s"
      SERVERFULL_RUNTIME_LOGGER_OUTPUT: "STDOUT"
      SERVERFULL_RUNTIME_LOGGER_LEVEL: "INFO"
      SERVERFULL_RUNTIME_STATS_OUTPUT: "NULL"
      SERVERFULL_RUNTIME_STATS_DATADOG_PACKETSIZE: 32768
      SERVERFULL_RUNTIME_STATS_DATADOG_TAGS: ""
      SERVERFULL_RUNTIME_STATS_DATADOG_FLUSHINTERVAL: "10s"
      SERVERFULL_RUNTIME_STATS_DATADOG_ADDRESS: "localhost:8125"
      SERVERFULL_RUNTIME_SIGNALS_INSTALLED: "OS"
      SERVERFULL_RUNTIME_SIGNALS_OS_SIGNALS: "15 2"
  gateway:
    build:
      context: .
      dockerfile: gateway.Dockerfile
    ports:
      - "8080:8080"
